### ISSUE TITLE
Das klappt nicht

### ISSUE THREAD

**Issue by vogti-01** [simon-wessendorf/wessendorf.software#1]
``` ts
import { varMap } from "../varMap";
``` 
Das funtzt nicht !??!!!!

**Comment by simon-wessendorf** [comment]
In der `varMap.ts` standen Variablen, die via JavaScript in die Seite eingefügt werden.
Genauer gesagt stand darin meine private Mail und Handy-Nummer.
Das hat den Vorteil, dass diese nicht so einfach von Crawlern gefunden werden können.
Die Datei stand in der Git-Ignore und entsprechend konnte sie bei dir nicht gefunden werden.

Ich lade diese Variablen jetzt durch eine `.env.local`, was unter anderem den Vorteil hat, dass ich eine `.env` mit Beispielwerten erstellen konnte. Es müsste jetzt bei dir also klappen!
